services:
  ubuntu-valgrind:
    container_name: mern
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
